### ISSUE TITLE
请问怎样在小程序安装paddle.js

### ISSUE THREAD

**Issue by FjjRichard** [SOVLOOKUP/PaddlejsInWechat#1]
请问怎样在小程序安装paddle.js
大佬，能加qq吗？527055685

**Comment by SOVLOOKUP** [comment]
添加paddlejs插件并且进行npm构建即可    
https://mp.weixin.qq.com/wxopen/plugindevdoc?appid=wx7138a7bb793608c3&token=1932652335&lang=zh_CN

**Comment by FjjRichard** [comment]
https://cloud.tencent.com/developer/article/1684093


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SOVLOOKUP/PaddlejsInWechat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月19日(星期五) 下午2:00
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [SOVLOOKUP/PaddlejsInWechat] 请问怎样在小程序安装paddle.js (#1)





 
Closed #1.
