### ISSUE TITLE
可以提供视频流上的写法吗?

### ISSUE THREAD

**Issue by ninetailskim** [SOVLOOKUP/PaddlejsInWechat#2]
如题,现在还只会选择一张图片传给网络一张这样,请问怎么作用在视频流上吗?也就是一直获取摄像头的数据这样

**Comment by SOVLOOKUP** [comment]
paddlejs暂时不支持视频流，如果支持了我会更新这个项目，但是js做视频流预测很可能流畅度不高

**Comment by ninetailskim** [comment]
> paddlejs暂时不支持视频流，如果支持了我会更新这个项目，但是js做视频流预测很可能流畅度不高

非常感谢～期待你的好消息～
