### ISSUE TITLE
大佬接口函数怎么写啊

### ISSUE THREAD

**Issue by mwaiting** [SOVLOOKUP/PaddlejsInWechat#4]

**Comment by SOVLOOKUP** [comment]
https://github.com/SOVLOOKUP/PaddlejsInWechat/blob/master/pages/index/index.js#L109

接口已经是写好的，根据你服务端的需要修改就可以

**Comment by mwaiting** [comment]
模型部署
1、建立两条记录一条为model，记录模型元信息
2、一条为parrots，这里放你的识别的物品信息，字段内容除了name可以自行修改
----------------
model、parrots这两个都是手动添加吗？有没文件可以直接导入啊，我看你截图parrots好几页啊

**Comment by SOVLOOKUP** [comment]
在微信云开发后台可以直接导入csv文件，这个是你自定义的待识别物品数据库
