### ISSUE TITLE
请问可以提供一下模型的json文件吗？

### ISSUE THREAD

**Issue by Chenyating** [SOVLOOKUP/PaddlejsInWechat#5]

**Comment by SOVLOOKUP** [comment]
![image](https://user-images.githubusercontent.com/53158137/136539842-3a616c88-2c47-4421-b75b-35fdc6d75a14.png)

模型 model.json 以及三个分片都是用 paddle 训练出来然后导出的，训练过程可以看这里：https://aistudio.baidu.com/aistudio/projectdetail/807809

**Comment by SOVLOOKUP** [comment]
https://paddlejs.cdn.bcebos.com/models/parrot/model.json

https://paddlejs.cdn.bcebos.com/models/parrot/chunk_1.dat

https://paddlejs.cdn.bcebos.com/models/parrot/chunk_2.dat

https://paddlejs.cdn.bcebos.com/models/parrot/chunk_3.dat

**Comment by SOVLOOKUP** [comment]
https://paddlejs.cdn.bcebos.com/models/parrot/model.json

https://paddlejs.cdn.bcebos.com/models/parrot/chunk_1.dat

https://paddlejs.cdn.bcebos.com/models/parrot/chunk_2.dat

https://paddlejs.cdn.bcebos.com/models/parrot/chunk_3.dat
